apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: branchprotector
spec:
  schedule: "*/30 * * * *"  # Run every 30 mn
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: branchprotector
    spec:
      template:
        spec:
          containers:
          - name: branchprotector
            # TODO(fejta): migrate to trusted prowjob
            image: gcr.io/k8s-prow/branchprotector:v20190731-cbc3a2509
            args:
            - --config-path=/etc/config/config.yaml
            - --confirm
            - --github-endpoint=http://ghproxy # prefer ghproxy
            - --github-endpoint=https://api.github.com
            - --github-token-path=/etc/github/oauth
            - --job-config-path=/etc/job-config
            volumeMounts:
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: config
              mountPath: /etc/config
              readOnly: true
            - name: job-config
              mountPath: /etc/job-config
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: oauth
            secret:
              secretName: oauth-token
          - name: config
            configMap:
              name: config
          - name: job-config
            configMap:
              name: job-config
          nodeSelector:
            prod: prow
